### ISSUE TITLE
GUI: coordinate display is wonky and still intersects with stones

### ISSUE THREAD

**Issue by NiklasZ** [NiklasZ/Go-Life-and-Death-Player#130]
The coordinate lines seem to be a bit wonky (not sure how you are painting them, but their positions seem to vary for some reason) and they stones cut into them on the right side:
![image](https://cloud.githubusercontent.com/assets/7795825/6691580/656fdb96-ccbf-11e4-9039-8483bc3920de.png)

**Comment by LausDaeus** [comment]
I would recommend moving them all to the edges of the board. The coordinates on the left look just fine.
